/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frmMenu;

import ConexionSQLDB.DataBaseConexion;
import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.SQLException;
import javax.lang.model.util.Types;
import oracle.jdbc.OracleTypes;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Aaron
 */
public class Funciones extends javax.swing.JFrame {

    /**
     * Creates new form Funciones
     */
    public Funciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnContar_ordenes_efectivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFuncion = new javax.swing.JTextArea();
        btnConsultar_horario = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnObtener_mantenimiento_anual = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aircone.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnContar_ordenes_efectivo.setText("contar_ordenes_efectivo");
        btnContar_ordenes_efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContar_ordenes_efectivoActionPerformed(evt);
            }
        });

        txtFuncion.setColumns(20);
        txtFuncion.setRows(5);
        jScrollPane1.setViewportView(txtFuncion);

        btnConsultar_horario.setText("consultar_horario");
        btnConsultar_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar_horarioActionPerformed(evt);
            }
        });

        jTextField1.setText("Consulta el HORARIO de las  sucursales donde sea igual  \"L-V: 7am-5pm\"");

        jTextField2.setText("Devuelve la cantidad de ordenes pagadas con efectivo ");

        btnObtener_mantenimiento_anual.setText("obtener_mantenimiento_anual");
        btnObtener_mantenimiento_anual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtener_mantenimiento_anualActionPerformed(evt);
            }
        });

        jTextField3.setText("Obtener reporte de mantenimientos que son mayores a 3 años");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObtener_mantenimiento_anual, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnContar_ordenes_efectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(btnConsultar_horario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(143, 143, 143))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContar_ordenes_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnAtras))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnObtener_mantenimiento_anual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("deprecation")
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        menu ir = new menu();
        ir.setVisible(true);
        hide();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnContar_ordenes_efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContar_ordenes_efectivoActionPerformed
        try {
            // Establecer la conexión con la base de datos
            Connection cnx = DataBaseConexion.getConnection();

            // Llamar a la función
            CallableStatement callableStatement = cnx.prepareCall("{? = call contar_ordenes_efectivo}");

            // Registrar el parámetro de salida como un número entero
            callableStatement.registerOutParameter(1, java.sql.Types.INTEGER);

            callableStatement.execute();

            // Obtener el resultado de la función
            int totalEfectivo = callableStatement.getInt(1);

            // Mostrar el resultado en tu JTextArea
            txtFuncion.setText("Cantidad de TOTAL_ORDENES con METODO_PAGO = EFECTIVO: " + totalEfectivo);

            // Cerrar las conexiones
            callableStatement.close();
            cnx.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Manejar la excepción según tus necesidades
        }


    }//GEN-LAST:event_btnContar_ordenes_efectivoActionPerformed

    private void btnConsultar_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar_horarioActionPerformed
        try {
            // Establecer la conexión con la base de datos
            Connection cnx = DataBaseConexion.getConnection();

            // Llamar a la función
            CallableStatement callableStatement = cnx.prepareCall("{? = call consultar_horario(?)}");

            // Registrar el parámetro de salida como cursor
            callableStatement.registerOutParameter(1, OracleTypes.CURSOR);

            // Establecer el valor del parámetro de entrada
            callableStatement.setString(2, "SUCURSAL");

            callableStatement.execute();

            // Recuperar el resultado del cursor
            ResultSet resultSet = (ResultSet) callableStatement.getObject(1);

            // Procesar el resultado y mostrarlo en tu JTextArea
            StringBuilder resultado = new StringBuilder();
            while (resultSet.next()) {
                int sucursalId = resultSet.getInt("SUCURSAL_ID");
                resultado.append("Sucursal ID: ").append(sucursalId).append("\n");
            }

            // Mostrar el resultado en tu JTextArea
            txtFuncion.setText(resultado.toString());

            // Cerrar las conexiones
            resultSet.close();
            callableStatement.close();
            cnx.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Manejar la excepción según tus necesidades
        }

    }//GEN-LAST:event_btnConsultar_horarioActionPerformed

    private void btnObtener_mantenimiento_anualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtener_mantenimiento_anualActionPerformed
        try {
            // Establecer la conexión con la base de datos
            Connection cnx = DataBaseConexion.getConnection();

            // Llamar a la función
            CallableStatement callableStatement = cnx.prepareCall("{? = call obtener_mantenimiento_anual}");

            // Registrar el parámetro de salida como cursor
            callableStatement.registerOutParameter(1, OracleTypes.CURSOR);

            callableStatement.execute();

            // Recuperar el resultado del cursor
            ResultSet resultSet = (ResultSet) callableStatement.getObject(1);

            // Procesar el resultado y mostrarlo en tu JTextArea
            StringBuilder resultado = new StringBuilder();
            while (resultSet.next()) {
                int mantenimientoAnual = resultSet.getInt("MANTENIMIENTO_ANUAL");
                resultado.append("MANTENIMIENTO_ANUAL: ").append(mantenimientoAnual).append("\n");
            }

            // Mostrar el resultado en tu JTextArea
            txtFuncion.setText(resultado.toString());

            // Cerrar las conexiones
            resultSet.close();
            callableStatement.close();
            cnx.close();
        } catch (SQLException e) {
            e.printStackTrace();
            // Manejar la excepción según tus necesidades
        }

    }//GEN-LAST:event_btnObtener_mantenimiento_anualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConsultar_horario;
    private javax.swing.JButton btnContar_ordenes_efectivo;
    private javax.swing.JButton btnObtener_mantenimiento_anual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextArea txtFuncion;
    // End of variables declaration//GEN-END:variables
}
