/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frmMenu;

import ConexionSQLDB.DataBaseConexion;
import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.SQLException;
import javax.lang.model.util.Types;
import oracle.jdbc.OracleTypes;
import java.sql.ResultSet;

/**
 *
 * @author Aaron
 */
public class ObtenerClientesActivos extends javax.swing.JFrame {

    /**
     * Creates new form ObtenerClientesActivos
     */
    public ObtenerClientesActivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtExec = new javax.swing.JTextField();
        btnEXECObtenerClientesActivos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        txtExec.setBackground(new java.awt.Color(255, 255, 255));

        btnEXECObtenerClientesActivos.setBackground(new java.awt.Color(0, 102, 204));
        btnEXECObtenerClientesActivos.setText("EXEC ObtenerClientesActivos");
        btnEXECObtenerClientesActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXECObtenerClientesActivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEXECObtenerClientesActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExec, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(txtExec, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnEXECObtenerClientesActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEXECObtenerClientesActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXECObtenerClientesActivosActionPerformed
        try {
    // Establecer la conexión con la base de datos
    Connection cnx = DataBaseConexion.getConnection();

    // Llamar al procedimiento almacenado
    CallableStatement callableStatement = cnx.prepareCall("{call ObtenerClientesActivos(?)}");

    // Registrar el parámetro de salida como cursor
    callableStatement.registerOutParameter(1, OracleTypes.CURSOR);

    callableStatement.execute();

    // Recuperar el resultado del cursor
    ResultSet resultSet = (ResultSet) callableStatement.getObject(1);

    // Procesar el resultado y mostrarlo en tu JTextArea
    StringBuilder resultado = new StringBuilder();
    while (resultSet.next()) {
        String info = resultSet.getString("info");
        resultado.append(info).append("\n");
    }

    // Mostrar el resultado en tu JTextArea
    txtExec.setText(resultado.toString());

    // Cerrar las conexiones
    resultSet.close();
    callableStatement.close();
    cnx.close();
} catch (SQLException e) {
    e.printStackTrace();
    // Manejar la excepción según tus necesidades
}


    }//GEN-LAST:event_btnEXECObtenerClientesActivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObtenerClientesActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObtenerClientesActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObtenerClientesActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObtenerClientesActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObtenerClientesActivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEXECObtenerClientesActivos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtExec;
    // End of variables declaration//GEN-END:variables
}
